// 统一文案文件：以后改页面文字主要改这里。
// common 是全站通用文案；pages 是各页面文案；meta 是浏览器标题和页面描述；copy 是页面正文。
// HTML 通过 data-copy 引用这些路径，例如 "pages.home.copy.underwater_rov_platforms"。
window.siteCopy = {
  "en": {
    "common": {
      "menu": {
        "open": "Open navigation",
        "close": "Close navigation"
      },
      "brand": {
        "topic": "Underwater Robotics",
        "company": "Beijing SquaDot Technology Ltd"
      },
      "nav": {
        "products": "Products",
        "applications": "Applications",
        "capabilities": "Capabilities",
        "cases": "Cases",
        "about": "About",
        "contact": "Contact"
      },
      "footer": {
        "website_label": "Website",
        "phone_label": "Phone",
        "quick_links_label": "Quick Links",
        "address_label": "Address",
        "address": "Room 3129, No. 86 Huoxing North Street, Huoxian Town, Tongzhou District, Beijing, P.R. China",
        "legal": "Copyright <span data-current-year></span> Squadot Tec. All rights reserved."
      }
    },
    "pages": {
      "home": {
        "meta": {
          "title": "Squadot Tec. | Underwater ROV Platforms",
          "description": "Squadot Tec. develops productized underwater ROV platforms for inspection, observation, confined access and payload-based mission support."
        },
        "copy": {
          "squadot_tec": "Squadot Tec.",
          "underwater_rov_platforms": "Underwater ROV platforms",
          "productized_underwater_platforms_for_inspection_observation_confined_access": "Productized underwater platforms for inspection, observation, confined access and payload-based mission support.",
          "inspection_platforms": "Inspection platforms",
          "mission_support": "Mission support",
          "payload_expansion": "Payload expansion",
          "view_products": "View Products",
          "five_platforms_cover_shallow_checks_confined_access_and": "Five platforms cover shallow checks, confined access and multi-payload inspection.",
          "we_are_squadot_tec": "We Are Squadot Tec.",
          "inspection_rov_systems": "Inspection ROV systems",
          "squadot_tec_develops_micro_to_medium_underwater_robot": "Squadot Tec. develops micro-to-medium underwater robot platforms for structural inspection, underwater observation, confined-space review, shallow-water checks and payload integration.",
          "delivery_covers_product_purchase_equipment_rental_field_support": "Delivery covers product purchase, equipment rental, field support and task-specific payload integration.",
          "start_with_platform_fit_rental_or_field_support": "Start with platform fit, rental or field support",
          "product_matrix": "Product Matrix",
          "five_platforms_defined_by_mission": "Five platforms, defined by mission",
          "compare_by_depth_mobility_and_payload_before_entering": "Compare by depth, mobility and payload before entering product detail",
          "hybrid_inspection_rov": "Hybrid inspection ROV",
          "item_100_m_class_platform_for_complex_waters_and": "100 m-class platform for complex waters and multi-payload inspection.",
          "agile_observation_rov": "Agile observation ROV",
          "for_fine_attitude_control_test_support_and_multi": "For fine attitude control, test support and multi-angle observation.",
          "close_range_work_rov": "Close-range work ROV",
          "for_depth_hold_close_inspection_and_light_work": "For depth hold, close inspection and light work expansion.",
          "shallow_water_pilot_rov": "Shallow-water pilot ROV",
          "portable_platform_for_rapid_deployment_and_short_shallow": "Portable platform for rapid deployment and short shallow-water checks.",
          "confined_access_rov": "Confined-access ROV",
          "item_10_m_class_unit_for_culverts_shafts_and": "10 m-class unit for culverts, shafts and narrow industrial spaces.",
          "applications_snapshot": "Applications Snapshot",
          "three_mission_directions": "Three mission directions",
          "map_task_type_to_platform_family_and_delivery": "Map task type to platform family and delivery mode",
          "hydraulic_inspection": "Hydraulic Inspection",
          "dams_and_hydraulic_assets": "Dams and hydraulic assets",
          "close_structural_review_without_diver_first_deployment_platforms": "Close structural review without diver-first deployment. Platforms: Challenge, SeaLeopard.",
          "complex_waters": "Complex Waters",
          "ports_and_nearshore_structures": "Ports and nearshore structures",
          "low_visibility_or_structure_rich_waters_requiring_sensor": "Low-visibility or structure-rich waters requiring sensor-ready payloads. Platform: SeaLeopard.",
          "constrained_access": "Constrained Access",
          "culverts_shafts_and_tanks": "Culverts, shafts and tanks",
          "visual_confirmation_where_larger_platforms_cannot_enter_platforms": "Visual confirmation where larger platforms cannot enter. Platforms: Linglong, Inspire.",
          "capabilities_snapshot": "Capabilities Snapshot",
          "engineering_control_sensing_and_delivery": "Engineering, control, sensing and delivery",
          "platform_engineering": "Platform engineering",
          "body_layout_sealing_maintenance_access_and_payload_space": "Body layout, sealing, maintenance access and payload space are designed as one platform system.",
          "motion_and_control": "Motion and control",
          "thruster_layout_depth_hold_and_operator_feedback_support": "Thruster layout, depth hold and operator feedback support stable inspection output.",
          "sensor_integration": "Sensor integration",
          "vision_sonar_water_quality_sensing_and_light_tools": "Vision, sonar, water-quality sensing and light tools are integrated by mission need.",
          "delivery_support": "Delivery support",
          "purchase_rental_field_support_and_payload_growth_follow": "Purchase, rental, field support and payload growth follow one delivery path.",
          "delivery_modes": "Delivery Modes",
          "delivery_models": "Delivery models",
          "delivery_is_matched_to_mission_scope_payload_work": "Delivery is matched to mission scope, payload work and site constraints",
          "purchase": "Purchase",
          "for_long_term_internal_operation_routine_inspection_and": "For long-term internal operation, routine inspection and self-owned equipment planning.",
          "rental": "Rental",
          "for_short_projects_early_validation_stages_and_temporary": "For short projects, early validation stages and temporary field deployment.",
          "platform_operator_support_and_field_side_coordination_can": "Platform, operator support and field-side coordination can be aligned to the actual task.",
          "project_expansion": "Project expansion",
          "add_sensing_support_frames_lighting_or_environment_modules": "Add sensing, support frames, lighting or environment modules around the target mission.",
          "beijing_squadot_technology_ltd": "Beijing SquaDot Technology Ltd",
          "underwater_rov_platforms_for_inspection_mission_support_and": "Underwater ROV platforms for inspection, mission support and payload integration.",
          "contact": "Contact",
          "define_the_mission_boundary": "Define the mission boundary",
          "share_depth_access_space_target_and_payload_expectations": "Share depth, access space, target and payload expectations to start a technical discussion.",
          "contact_us": "Contact Us"
        }
      },
      "products": {
        "meta": {
          "title": "Products | Squadot Tec.",
          "description": "Compare five underwater ROV platforms for inspection, observation, confined access and mission support."
        },
        "copy": {
          "products": "Products",
          "five_platforms_by_mission_boundary": "Five platforms by mission boundary",
          "the_portfolio_spans_micro_to_medium_platforms_matched": "The portfolio spans micro to medium platforms, matched by depth, access space, observation target, payload need and delivery model.",
          "item_100_m_class_range": "100 m-class range",
          "constrained_access": "Constrained access",
          "purchase_rental": "Purchase / rental",
          "compare_platforms": "Compare Platforms",
          "start_with_depth_access_space_and_payload_direction": "Start with depth, access space and payload direction before platform detail.",
          "overview": "Overview",
          "five_platforms_clear_selection_path": "Five platforms, clear selection path",
          "medium_hybrid_rov": "Medium hybrid ROV",
          "item_100_m_class_platform_for_complex_waters_and": "100 m-class platform for complex waters and payload growth.",
          "agile_observation_rov": "Agile observation ROV",
          "for_fine_attitude_control_experiment_support_and_multi": "For fine attitude control, experiment support and multi-angle observation.",
          "close_range_work_rov": "Close-range work ROV",
          "six_thruster_base_with_an_upgrade_path_for": "Six-thruster base with an upgrade path for eight-thruster work logic.",
          "shallow_pilot_rov": "Shallow pilot ROV",
          "portable_platform_for_short_shallow_water_checks_and": "Portable platform for short shallow-water checks and fast site entry.",
          "confined_access_rov": "Confined-access ROV",
          "item_10_m_class_unit_for_culverts_shafts_and": "10 m-class unit for culverts, shafts and box channels.",
          "medium_hybrid_inspection_rov": "Medium hybrid inspection ROV",
          "designed_for_complex_water_inspection_mission_stability_and": "Designed for complex-water inspection, mission stability and payload growth around reservoirs, dams, nearshore structures and environmental monitoring.",
          "item_8_thrusters": "8 thrusters",
          "multi_payload": "Multi-payload",
          "complex_waters": "Complex waters",
          "platform_role": "Platform role",
          "medium_hybrid_platform_for_inspection_observation_survey_support": "Medium hybrid platform for inspection, observation, survey support and payload-based mission growth.",
          "standard_configuration": "Standard configuration",
          "hd_visual_observation": "HD visual observation",
          "depth_attitude_and_heading_feedback": "Depth, attitude and heading feedback",
          "ground_station_monitoring": "Ground-station monitoring",
          "optional_modules": "Optional modules",
          "dvl": "DVL",
          "scanning_sonar": "Scanning sonar",
          "water_quality_multiparameter_sensing": "Water-quality multiparameter sensing",
          "manipulator_or_sampling_tools": "Manipulator or sampling tools",
          "project_expansion": "Project expansion",
          "optional_binocular_vision_industrial_pc_edge_computing_and": "Optional binocular vision, industrial PC, edge computing and task frames are handled as project scope; R&amp;D reserves are discussed separately.",
          "typical_tasks_structural_inspection_engineering_observation_complex_water": "Typical tasks: structural inspection, engineering observation, complex-water navigation support and multi-sensor packages.",
          "designed_for_maneuverability_multi_angle_viewing_fine_attitude": "Designed for maneuverability, multi-angle viewing, fine attitude control and underwater test support.",
          "fine_attitude_control": "Fine attitude control",
          "data_collection": "Data collection",
          "compact_platform_for_fine_inspection_underwater_tests_research": "Compact platform for fine inspection, underwater tests, research observation and engineering review.",
          "manual_control": "Manual control",
          "multi_axis_attitude_control": "Multi-axis attitude control",
          "manipulator": "Manipulator",
          "small_water_quality_sensors": "Small water-quality sensors",
          "additional_lighting": "Additional lighting",
          "custom_task_frames_external_modules_and_collection_attachments": "Custom task frames, external modules and collection attachments are handled as project-specific scope.",
          "typical_tasks_precision_observation_experiment_support_multi_angle": "Typical tasks: precision observation, experiment support, multi-angle target review and compact deep-water inspection.",
          "work_class_inspection_rov": "Work-class inspection ROV",
          "close_range_platform_with_six_thruster_base_and": "Close-range platform with six-thruster base and eight-thruster upgrade path for waterworks, pump stations and gate chambers.",
          "depth_hold": "Depth hold",
          "light_work": "Light work",
          "for_close_inspection_stable_hovering_directional_review_and": "For close inspection, stable hovering, directional review and light accessory expansion.",
          "basic_attitude_control": "Basic attitude control",
          "px4_ardusub_qgroundcontrol_control_path": "PX4 / ArduSub / QGroundControl control path",
          "manipulator_claw": "Manipulator claw",
          "gimbal": "Gimbal",
          "lighting_system": "Lighting system",
          "custom_tether_length": "Custom tether length",
          "eight_thruster_upgrade_custom_interface_boards_and_task": "Eight-thruster upgrade, custom interface boards and task accessories are available for light work scenarios.",
          "typical_tasks_hydraulic_review_pump_station_inspection_gate": "Typical tasks: hydraulic review, pump-station inspection, gate chamber observation and close-range visual confirmation.",
          "portable_shallow_water_rov": "Portable shallow-water ROV",
          "fast_entry_platform_for_shallow_pilot_checks_short": "Fast-entry platform for shallow pilot checks, short reviews and trial deployment in ponds, pits, tanks and nearshore shallows.",
          "item_6_thrusters": "6 thrusters",
          "fast_deployment": "Fast deployment",
          "for_shallow_pilot_checks_initial_judgement_short_reviews": "For shallow pilot checks, initial judgement, short reviews and low-threshold field entry.",
          "network_communication": "Network communication",
          "portable_pvc_tube_structure_logic": "Portable PVC-tube structure logic",
          "visual_add_ons": "Visual add-ons",
          "lighting": "Lighting",
          "shallow_water_sensing_modules": "Shallow-water sensing modules",
          "quick_release_accessories_collision_protection_and_shallow_water": "Quick-release accessories, collision protection and shallow-water detection modules can be configured on site.",
          "typical_tasks_shallow_pilot_checks_pond_review_short": "Typical tasks: shallow pilot checks, pond review, short validation and rapid site entry.",
          "compact_confined_access_rov": "Compact confined-access ROV",
          "constrained_access_unit_for_culverts_gate_slots_shafts": "Constrained-access unit for culverts, gate slots, shafts, box channels and other shallow industrial water spaces.",
          "lightweight": "Lightweight",
          "for_close_visual_review_anomaly_confirmation_and_rapid": "For close visual review, anomaly confirmation and rapid entry into narrow shallow spaces.",
          "lightweight_compact_body": "Lightweight compact body",
          "shallow_water_video_observation": "Shallow-water video observation",
          "rapid_single_operator_deployment_logic": "Rapid single-operator deployment logic",
          "shallow_water_water_quality_sensing": "Shallow-water water-quality sensing",
          "small_manipulator_tools": "Small manipulator tools",
          "collision_protection_structures_narrow_space_brackets_and_lightweight": "Collision-protection structures, narrow-space brackets and lightweight task accessories can be configured by project.",
          "typical_tasks_culvert_review_shaft_inspection_shallow_anomaly": "Typical tasks: culvert review, shaft inspection, shallow anomaly confirmation and confined-space pilot checks.",
          "support_logic": "Support Logic",
          "standard_first_mission_growth_second": "Standard first, mission growth second",
          "most_projects_should_start_with_a_deliverable_standard": "Most projects should start with a deliverable standard platform, then expand only where sensing, frames or delivery mode require it.",
          "standard_platform": "Standard platform",
          "use_the_current_direct_delivery_platform_as_the": "Use the current direct-delivery platform as the first matching base.",
          "module_growth": "Module growth",
          "add_sensing_lighting_sampling_or_support_frames_only": "Add sensing, lighting, sampling or support frames only where the mission needs them.",
          "delivery_alignment": "Delivery alignment",
          "purchase_rental_or_mission_support_should_follow_task": "Purchase, rental or mission support should follow task cycle and field intensity.",
          "first_platform_recommendation": "First platform recommendation",
          "share_depth_range_entry_size_and_payload_direction": "Share depth range, entry size and payload direction to narrow the platform path.",
          "start_with_your_mission": "Start with Your Mission",
          "beijing_squadot_technology_ltd": "Beijing SquaDot Technology Ltd",
          "five_platform_product_range_for_inspection_observation_and": "Five-platform product range for inspection, observation and mission support.",
          "selection_logic": "Selection Logic",
          "select_by_mission_boundary": "Select by mission boundary",
          "share_depth_access_space_target_payload_needs_and": "Share depth, access space, target, payload needs and delivery model to identify the platform family."
        }
      },
      "applications": {
        "meta": {
          "title": "Applications | Squadot Tec.",
          "description": "Match underwater ROV platforms to hydraulic inspection, nearshore assets, shallow-water checks and confined access tasks."
        },
        "copy": {
          "applications": "Applications",
          "select_platforms_by_scene_constraints": "Select platforms by scene constraints",
          "scenes_are_organized_by_operating_depth_access_space": "Scenes are organized by operating depth, access space, target, stability and payload needs.",
          "depth_range": "Depth range",
          "space_limit": "Space limit",
          "payload_need": "Payload need",
          "view_selection_logic": "View Selection Logic",
          "use_site_conditions_to_narrow_platform_fit_before": "Use site conditions to narrow platform fit before comparing hardware.",
          "matching_logic": "Matching Logic",
          "four_inputs_for_platform_fit": "Four inputs for platform fit",
          "depth_hovering_and_operating_duration_quickly_separate_platform": "Depth, hovering and operating duration quickly separate platform families.",
          "space_boundary": "Space boundary",
          "open_water_culverts_shafts_and_gate_slots_require": "Open water, culverts, shafts and gate slots require different access logic.",
          "observation_demand": "Observation demand",
          "routine_review_precision_observation_and_experiment_support_require": "Routine review, precision observation and experiment support require different stability levels.",
          "payload_and_delivery": "Payload and delivery",
          "some_missions_need_only_video_others_require_sonar": "Some missions need only video; others require sonar, sensing, payloads or field support.",
          "scene_01": "Scene 01",
          "ports_and_nearshore_assets": "Ports and nearshore assets",
          "low_visibility_piles_cables_sediment_or_path_support": "Low visibility, piles, cables, sediment or path-support needs move the task beyond basic video review.",
          "client_problem": "Client problem",
          "single_view_observation_is_often_insufficient_in_structure": "Single-view observation is often insufficient in structure-rich waters.",
          "recommended_platform": "Recommended platform",
          "sealeopard_with_sonar_dvl_or_environmental_sensing_when": "SeaLeopard, with sonar, DVL or environmental sensing when required.",
          "delivery_platform_sensing_module_and_mission_support_product": "Delivery: platform, sensing module and mission support. Product: SeaLeopard.",
          "scene_02": "Scene 02",
          "dams_and_hydraulic_assets": "Dams and hydraulic assets",
          "these_tasks_require_stable_close_viewing_depth_hold": "These tasks require stable close viewing, depth hold and condition confirmation without diver-first deployment.",
          "operators_need_clear_target_surface_imagery_while_holding": "Operators need clear target-surface imagery while holding a stable viewing distance.",
          "challenge_for_routine_work_class_review_sealeopard_where": "Challenge for routine work-class review; SeaLeopard where more payload or stability is required.",
          "delivery_purchase_or_mission_support_depending_on_task": "Delivery: purchase or mission support, depending on task frequency.",
          "scene_03": "Scene 03",
          "precision_observation_and_underwater_tests": "Precision observation and underwater tests",
          "these_missions_require_fine_attitude_control_repeatable_response": "These missions require fine attitude control, repeatable response and stable target alignment.",
          "observation_quality_drops_quickly_when_posture_stability_is": "Observation quality drops quickly when posture stability is insufficient.",
          "hammerhead_with_multi_axis_control_and_task_specific": "Hammerhead with multi-axis control and task-specific support frames.",
          "delivery_rental_test_support_or_project_expansion_around": "Delivery: rental, test support or project expansion around the experiment setup.",
          "scene_04": "Scene 04",
          "shallow_pilot_checks_and_tanks": "Shallow pilot checks and tanks",
          "fast_deployment_and_low_operating_threshold_matter_more": "Fast deployment and low operating threshold matter more than heavy payload capacity.",
          "large_platforms_are_often_unnecessary_in_ponds_pits": "Large platforms are often unnecessary in ponds, pits and trial tanks.",
          "inspire_for_quick_entry_and_shallow_water_review": "Inspire for quick entry and shallow-water review.",
          "delivery_rental_or_short_mission_support_for_pilot": "Delivery: rental or short mission support for pilot judgement and validation.",
          "scene_05": "Scene 05",
          "confined_industrial_spaces": "Confined industrial spaces",
          "culverts_gate_slots_shafts_box_channels_and_tanks": "Culverts, gate slots, shafts, box channels and tanks prioritize compact entry over broad-water mobility.",
          "large_platforms_cannot_enter_reliably_but_anomaly_confirmation": "Large platforms cannot enter reliably, but anomaly confirmation is still required.",
          "linglong_first_inspire_when_the_space_is_less": "Linglong first; Inspire when the space is less constrained and the task remains shallow.",
          "delivery_portable_inspection_support_shallow_anomaly_review_and": "Delivery: portable inspection support, shallow anomaly review and light module expansion.",
          "scene_based_recommendation": "Scene-based recommendation",
          "start_with_depth_entry_size_target_and_payload": "Start with depth, entry size, target and payload expectations.",
          "start_the_discussion": "Start the Discussion",
          "beijing_squadot_technology_ltd": "Beijing SquaDot Technology Ltd",
          "scene_led_platform_matching_for_underwater_inspection_and": "Scene-led platform matching for underwater inspection and observation.",
          "next_step": "Next Step",
          "site_specific_platform_direction": "Site-specific platform direction",
          "provide_depth_entry_size_target_and_payload_expectations": "Provide depth, entry size, target and payload expectations to define the first platform direction.",
          "start_contact": "Start Contact"
        }
      },
      "capabilities": {
        "meta": {
          "title": "Capabilities | Squadot Tec.",
          "description": "Review platform design, sealing logic, control, sensing integration and mission delivery capabilities."
        },
        "copy": {
          "capabilities": "Capabilities",
          "platform_control_mission_integration": "Platform, control, mission integration",
          "capability_is_organized_around_platform_design_sealing_control": "Capability is organized around platform design, sealing, control, payload integration and field support.",
          "platform_body": "Platform body",
          "control_loop": "Control loop",
          "mission_integration": "Mission integration",
          "view_capability_layers": "View Capability Layers",
          "review_standard_capability_optional_modules_and_project_expansion": "Review standard capability, optional modules and project expansion by layer.",
          "core_capability": "Core Capability",
          "six_capability_blocks": "Six capability blocks",
          "platform_engineering": "Platform engineering",
          "structure_size_envelope_internal_layout_and_maintenance_access": "Structure, size envelope, internal layout and maintenance access are designed as one platform system.",
          "sealing_and_pressure_logic": "Sealing and pressure logic",
          "reliable_underwater_use_depends_on_sealing_cable_entry": "Reliable underwater use depends on sealing, cable entry and maintenance logic, not isolated waterproof parts.",
          "propulsion_and_motion_control": "Propulsion and motion control",
          "thruster_layout_depth_hold_and_stable_viewing_behavior": "Thruster layout, depth hold and stable viewing behavior determine inspection quality.",
          "ground_station_and_operator_loop": "Ground station and operator loop",
          "monitoring_operator_feedback_and_task_adjustment_must_stay": "Monitoring, operator feedback and task adjustment must stay in one control loop.",
          "payload_and_sensor_integration": "Payload and sensor integration",
          "video_sonar_sampling_water_quality_sensing_and_manipulator": "Video, sonar, sampling, water-quality sensing and manipulator work are integrated by mission need.",
          "mission_support_and_project_expansion": "Mission support and project expansion",
          "platform_selection_field_support_and_project_expansion_are": "Platform selection, field support and project expansion are part of the delivery scope.",
          "capability_layer": "Capability Layer",
          "standard_optional_and_project_layers": "Standard, optional and project layers",
          "layered_capability_keeps_standard_configuration_optional_modules_and": "Layered capability keeps standard configuration, optional modules and project support clear.",
          "layer_01": "Layer 01",
          "standard_configuration_deliverable_platform_capability": "Standard configuration: deliverable platform capability.",
          "layer_02": "Layer 02",
          "optional_modules_add_ons_that_do_not_require": "Optional modules: add-ons that do not require platform redesign.",
          "layer_03": "Layer 03",
          "project_expansion_mission_driven_frames_interfaces_and_system": "Project expansion: mission-driven frames, interfaces and system changes.",
          "layer_04": "Layer 04",
          "r_and_d_reserve_discussed_separately_not_a": "R&amp;D reserve: discussed separately, not a default delivery promise.",
          "delivery_models": "Delivery Models",
          "capability_mapped_to_delivery": "Capability mapped to delivery",
          "platform_purchase": "Platform purchase",
          "for_users_building_regular_in_house_inspection_and": "For users building regular in-house inspection and observation capability.",
          "equipment_rental": "Equipment rental",
          "for_short_cycle_missions_validation_work_and_temporary": "For short-cycle missions, validation work and temporary field review.",
          "mission_support": "Mission support",
          "for_customers_who_need_platform_plus_field_side": "For customers who need platform plus field-side operator or technical coordination.",
          "project_expansion": "Project expansion",
          "for_missions_that_require_sensing_brackets_environment_modules": "For missions that require sensing, brackets, environment modules or custom support interfaces.",
          "discuss_capability_by_layer_then_map_it_to": "Discuss capability by layer, then map it to depth, access space and payload.",
          "capability_match": "Capability match",
          "start_with_depth_scene_and_payload_expectations_to": "Start with depth, scene and payload expectations to narrow the usable capability layer.",
          "start_capability_match": "Start Capability Match",
          "beijing_squadot_technology_ltd": "Beijing SquaDot Technology Ltd",
          "engineering_capability_across_platform_control_sensing_and_field": "Engineering capability across platform, control, sensing and field delivery.",
          "contact": "Contact",
          "mission_based_capability_match": "Mission-based capability match",
          "start_with_depth_entry_space_target_and_module": "Start with depth, entry space, target and module needs to match the capability layer and delivery path.",
          "start_contact": "Start Contact"
        }
      },
      "cases": {
        "meta": {
          "title": "Cases | Squadot Tec.",
          "description": "Review representative cases for nearshore inspection, hydraulic structures, test support, shallow checks and confined access."
        },
        "copy": {
          "cases": "Cases",
          "cases_by_mission_type": "Cases by mission type",
          "representative_cases_show_platform_fit_observation_quality_control": "Representative cases show platform fit, observation quality, control behavior and delivery scope.",
          "scene_fit": "Scene fit",
          "control_quality": "Control quality",
          "delivery_path": "Delivery path",
          "browse_cases": "Browse Cases",
          "use_each_case_as_a_reference_for_similar": "Use each case as a reference for similar site conditions and delivery needs.",
          "case_01": "Case 01",
          "nearshore_inspection": "Nearshore inspection",
          "for_structure_rich_waters_where_path_support_environment": "For structure-rich waters where path support, environment awareness and collision-risk reduction matter.",
          "client_problem": "Client problem",
          "piles_cables_sediment_and_low_visibility_make_single": "Piles, cables, sediment and low visibility make single-mode observation insufficient.",
          "platform_capability": "Platform / capability",
          "sealeopard_with_scanning_sonar_dvl_and_environmental_sensing": "SeaLeopard with scanning sonar, DVL and environmental sensing when required.",
          "value_stronger_environment_awareness_and_path_support_logic": "Value: stronger environment awareness and path-support logic. Product: SeaLeopard.",
          "case_02": "Case 02",
          "precision_observation": "Precision observation",
          "focused_on_precise_operator_response_controlled_posture_and": "Focused on precise operator response, controlled posture and repeatable target alignment.",
          "observation_quality_depends_directly_on_posture_stability_and": "Observation quality depends directly on posture stability and angle control.",
          "hammerhead_with_multi_axis_motion_control_and_task": "Hammerhead with multi-axis motion control and task-specific support frames.",
          "value_better_posture_stability_and_execution_precision_product": "Value: better posture stability and execution precision. Product: Hammerhead.",
          "case_03": "Case 03",
          "hydraulic_inspection": "Hydraulic inspection",
          "routine_structural_review_where_close_range_imaging_and": "Routine structural review where close-range imaging and stable hovering matter more than payload complexity.",
          "the_structure_must_be_inspected_without_organizing_diver": "The structure must be inspected without organizing diver-first access.",
          "challenge_with_hd_visual_observation_depth_hold_and": "Challenge with HD visual observation, depth hold and ground-station monitoring.",
          "value_reviewable_structure_records_for_follow_up_maintenance": "Value: reviewable structure records for follow-up maintenance. Product: Challenge.",
          "case_04": "Case 04",
          "shallow_pilot_checks": "Shallow pilot checks",
          "for_quick_judgement_close_review_and_fast_entry": "For quick judgement, close review and fast entry where small deployable platforms are more efficient.",
          "the_work_is_short_cycle_and_does_not": "The work is short-cycle and does not justify larger equipment deployment.",
          "inspire_with_fast_deployment_network_communication_and_six": "Inspire with fast deployment, network communication and six-thruster shallow-water control.",
          "value_fast_first_pass_judgement_and_low_threshold": "Value: fast first-pass judgement and low-threshold field review. Product: Inspire.",
          "case_05": "Case 05",
          "confined_space_inspection": "Confined-space inspection",
          "when_culverts_shafts_gate_slots_or_box_channels": "When culverts, shafts, gate slots or box channels make entry size the main selection factor.",
          "large_platforms_cannot_enter_but_local_anomaly_review": "Large platforms cannot enter, but local anomaly review and record keeping still have to be completed.",
          "linglong_with_compact_body_shallow_water_video_review": "Linglong with compact body, shallow-water video review and rapid deployment.",
          "value_lower_entry_threshold_and_faster_anomaly_confirmation": "Value: lower entry threshold and faster anomaly confirmation. Product: Linglong.",
          "case_value": "Case Value",
          "what_cases_clarify": "What cases clarify",
          "each_case_highlights_scene_fit_execution_method_and": "Each case highlights scene fit, execution method and usable delivery range.",
          "mission_fit": "Mission fit",
          "case_descriptions_are_organized_around_scene_conditions_and": "Case descriptions are organized around scene conditions and platform fit.",
          "scope_clarity": "Scope clarity",
          "the_page_focuses_on_representative_mission_profiles_rather": "The page focuses on representative mission profiles rather than catalog-style listing.",
          "capability_proof": "Capability proof",
          "each_case_shows_platform_fit_control_quality_and": "Each case shows platform fit, control quality and mission integration logic.",
          "next_step": "Next step",
          "the_page_is_designed_to_support_discussion_around": "The page is designed to support discussion around similar site conditions and output goals.",
          "similar_mission_discussion": "Similar mission discussion",
          "share_site_conditions_and_desired_output_to_map": "Share site conditions and desired output to map the closest platform and support mode.",
          "start_the_discussion": "Start the Discussion",
          "beijing_squadot_technology_ltd": "Beijing SquaDot Technology Ltd",
          "mission_aligned_cases_for_underwater_observation_inspection_and": "Mission-aligned cases for underwater observation, inspection and support.",
          "contact": "Contact",
          "comparable_mission_profile": "Comparable mission profile",
          "send_site_conditions_and_desired_output_to_map": "Send site conditions and desired output to map the closest platform and support model.",
          "start_contact": "Start Contact"
        }
      },
      "about": {
        "meta": {
          "title": "About | Squadot Tec.",
          "description": "Learn about Squadot Tec. as a productized engineering team for underwater robot platforms and mission delivery."
        },
        "copy": {
          "about_squadot_tec": "About Squadot Tec.",
          "engineering_team_for_underwater_systems": "Engineering team for underwater systems",
          "squadot_tec_focuses_on_underwater_observation_structural_inspection": "Squadot Tec. focuses on underwater observation, structural inspection, confined access, shallow-water review and payload integration.",
          "engineering_team": "Engineering team",
          "platform_delivery": "Platform delivery",
          "project_growth": "Project growth",
          "see_team_logic": "See Team Logic",
          "understand_the_team_through_platform_engineering_sensing_control": "Understand the team through platform engineering, sensing, control and delivery.",
          "identity": "Identity",
          "productized_engineering_team": "Productized engineering team",
          "productized_engineering_team_for_underwater_robot_platforms_and": "Productized engineering team for underwater robot platforms and mission support.",
          "current_offering": "Current offering",
          "micro_to_medium_platforms_rental_purchase_field_support": "Micro-to-medium platforms, rental, purchase, field support and payload integration.",
          "scene_focus": "Scene focus",
          "hydraulic_structures_nearshore_assets_ponds_shafts_culverts_and": "Hydraulic structures, nearshore assets, ponds, shafts, culverts and confined industrial water spaces.",
          "delivery_logic": "Delivery logic",
          "begin_with_a_standard_platform_then_expand_payloads": "Begin with a standard platform, then expand payloads, frames and delivery mode as needed.",
          "team_background": "Team Background",
          "platform_sensing_control_delivery": "Platform, sensing, control, delivery",
          "engineering_background": "Engineering background",
          "team_background_spans_acoustics_underwater_robotics_navigation_slam": "Team background spans acoustics, underwater robotics, navigation, SLAM and underwater system design.",
          "platform_engineering": "Platform engineering",
          "capability_covers_rov_auv_structure_design_watertight_components": "Capability covers ROV/AUV structure design, watertight components, control systems and field deployment.",
          "perception_and_navigation": "Perception and navigation",
          "work_covers_sonar_slam_path_planning_image_enhancement": "Work covers sonar SLAM, path planning, image enhancement and multi-sensor fusion.",
          "system_integration": "System integration",
          "software_integration_ground_station_monitoring_and_field_execution": "Software integration, ground-station monitoring and field execution are part of the delivery system.",
          "company_approach": "Company Approach",
          "standard_platform_first_mission_growth_second": "Standard platform first, mission growth second",
          "step_01": "Step 01",
          "choose_the_closest_standard_platform_by_depth_access": "Choose the closest standard platform by depth, access space and motion requirement.",
          "step_02": "Step 02",
          "add_sensing_lighting_sampling_or_support_frames_only": "Add sensing, lighting, sampling or support frames only when the mission requires them.",
          "step_03": "Step 03",
          "align_purchase_rental_or_mission_support_with_the": "Align purchase, rental or mission support with the project cycle.",
          "engineering_discussion": "Engineering discussion",
          "share_site_conditions_delivery_mode_and_module_expectations": "Share site conditions, delivery mode and module expectations to define the right path.",
          "start_contact": "Start Contact",
          "beijing_squadot_technology_ltd": "Beijing SquaDot Technology Ltd",
          "productized_engineering_team_for_underwater_robot_systems_and": "Productized engineering team for underwater robot systems and mission support.",
          "contact": "Contact",
          "mission_boundary": "Mission boundary",
          "start_with_depth_entry_size_target_type_and": "Start with depth, entry size, target type and module expectations."
        }
      },
      "contact": {
        "meta": {
          "title": "Contact | Squadot Tec.",
          "description": "Contact Squadot Tec. with depth, access space, observation target, payload needs and delivery timeline."
        },
        "copy": {
          "contact": "Contact",
          "start_with_depth_access_and_payload": "Start with depth, access and payload",
          "the_most_useful_first_inputs_are_operating_depth": "The most useful first inputs are operating depth, entry size, observation target, payload need and delivery timeline.",
          "depth_range": "Depth range",
          "entry_size": "Entry size",
          "delivery_timeline": "Delivery timeline",
          "view_contact_info": "View Contact Info",
          "a_short_mission_brief_is_enough_to_begin": "A short mission brief is enough to begin platform matching.",
          "direct_contact": "Direct contact",
          "company": "Company",
          "squadot_tec": "Squadot Tec.",
          "beijing_squadot_technology_ltd": "Beijing SquaDot Technology Ltd",
          "website": "Website",
          "phone": "Phone",
          "address": "Address",
          "room_3129_no_86_huoxing_north_street_huoxian": "Room 3129, No. 86 Huoxing North Street, Huoxian Town, Tongzhou District, Beijing, P.R. China",
          "mission_brief": "Mission Brief",
          "six_inputs_for_the_first_brief": "Six inputs for the first brief",
          "item_01_depth_range": "01. Depth range",
          "operating_depth_and_whether_depth_hold_is_required": "Operating depth and whether depth hold is required.",
          "item_02_entry_size": "02. Entry size",
          "opening_size_channel_width_and_whether_the_site": "Opening size, channel width and whether the site is a confined space.",
          "item_03_observation_target": "03. Observation target",
          "structure_sediment_anomaly_point_test_setup_or_environmental": "Structure, sediment, anomaly point, test setup or environmental condition.",
          "item_04_payload_need": "04. Payload need",
          "video_only_or_additional_sonar_sampling_water_quality": "Video only, or additional sonar, sampling, water-quality or manipulator modules.",
          "item_05_delivery_model": "05. Delivery model",
          "purchase_rental_short_field_support_or_project_specific": "Purchase, rental, short field support or project-specific development.",
          "item_06_timeline": "06. Timeline",
          "start_date_and_whether_the_work_is_one": "Start date and whether the work is one-off or recurring.",
          "contact_base": "Contact Base",
          "project_communication_channels": "Project communication channels",
          "use_phone_website_and_company_address_to_start": "Use phone, website and company address to start a focused discussion around mission conditions and delivery needs.",
          "chinese_address": "Chinese address",
          "english_address": "English address",
          "first_mission_brief": "First mission brief",
          "call_directly_or_send_a_short_mission_brief": "Call directly or send a short mission brief through the website channel.",
          "call_now": "Call Now",
          "underwater_robot_platforms_mission_support_and_project_specific": "Underwater robot platforms, mission support and project-specific integration.",
          "talk_to_us": "Talk to Us",
          "initial_platform_direction": "Initial platform direction"
        }
      }
    }
  },
  "zh": {
    "common": {
      "menu": {
        "open": "打开导航",
        "close": "关闭导航"
      },
      "brand": {
        "topic": "水下机器人",
        "company": "北京方点科技有限公司"
      },
      "nav": {
        "products": "产品",
        "applications": "场景",
        "capabilities": "能力",
        "cases": "案例",
        "about": "关于",
        "contact": "联系"
      },
      "footer": {
        "website_label": "官网",
        "phone_label": "电话",
        "quick_links_label": "快速链接",
        "address_label": "地址",
        "address": "北京市通州区漷县镇漷兴北大街86号院3129室",
        "legal": "版权所有 <span data-current-year></span> Squadot Tec. 保留所有权利。"
      }
    },
    "pages": {
      "home": {
        "meta": {
          "title": "Squadot Tec. | 水下 ROV 平台",
          "description": "Squadot Tec. 提供面向巡检、观测、受限空间进入与挂载任务支持的产品化水下平台。"
        },
        "copy": {
          "squadot_tec": "Squadot Tec.",
          "underwater_rov_platforms": "水下 ROV 平台",
          "productized_underwater_platforms_for_inspection_observation_confined_access": "面向巡检、观测、受限空间进入与挂载任务支持的产品化水下平台。",
          "inspection_platforms": "巡检平台",
          "mission_support": "任务支持",
          "payload_expansion": "挂载扩展",
          "view_products": "查看产品",
          "five_platforms_cover_shallow_checks_confined_access_and": "五个平台覆盖浅水检查、受限空间进入与多挂载巡检。",
          "we_are_squadot_tec": "我们是谁",
          "inspection_rov_systems": "巡检 ROV 系统",
          "squadot_tec_develops_micro_to_medium_underwater_robot": "Squadot Tec. 开发微型至中型水下机器人平台，服务结构巡检、水下观测、受限空间复核、浅水检查与挂载集成。",
          "delivery_covers_product_purchase_equipment_rental_field_support": "交付覆盖产品采购、设备租赁、现场支持与任务专用挂载集成。",
          "start_with_platform_fit_rental_or_field_support": "从平台适配、租赁或现场支持开始",
          "product_matrix": "产品矩阵",
          "five_platforms_defined_by_mission": "五个平台，按任务定义",
          "compare_by_depth_mobility_and_payload_before_entering": "先比较水深、机动性与挂载，再进入产品细节",
          "hybrid_inspection_rov": "混合巡检 ROV",
          "item_100_m_class_platform_for_complex_waters_and": "100 m 级平台，面向复杂水域与多挂载巡检。",
          "agile_observation_rov": "高机动观测 ROV",
          "for_fine_attitude_control_test_support_and_multi": "用于精细姿态控制、试验支持与多角度观测。",
          "close_range_work_rov": "近距作业 ROV",
          "for_depth_hold_close_inspection_and_light_work": "用于定深、近距巡检与轻作业扩展。",
          "shallow_water_pilot_rov": "浅水先导 ROV",
          "portable_platform_for_rapid_deployment_and_short_shallow": "便携平台，用于快速部署和短周期浅水检查。",
          "confined_access_rov": "受限空间 ROV",
          "item_10_m_class_unit_for_culverts_shafts_and": "10 m 级设备，用于涵洞、井室与狭窄工业空间。",
          "applications_snapshot": "场景摘要",
          "three_mission_directions": "三类任务方向",
          "map_task_type_to_platform_family_and_delivery": "将任务类型映射到平台系列和交付方式",
          "hydraulic_inspection": "水工巡检",
          "dams_and_hydraulic_assets": "大坝与水工资产",
          "close_structural_review_without_diver_first_deployment_platforms": "无需潜水员先行进入，即可完成近距结构复核。平台：Challenge、SeaLeopard。",
          "complex_waters": "复杂水域",
          "ports_and_nearshore_structures": "港口与近岸结构",
          "low_visibility_or_structure_rich_waters_requiring_sensor": "低能见度或结构密集水域，需要可扩展传感挂载。平台：SeaLeopard。",
          "constrained_access": "受限进入",
          "culverts_shafts_and_tanks": "涵洞、井室与罐体",
          "visual_confirmation_where_larger_platforms_cannot_enter_platforms": "大型平台无法进入时完成视觉确认。平台：Linglong、Inspire。",
          "capabilities_snapshot": "能力摘要",
          "engineering_control_sensing_and_delivery": "工程、控制、感知与交付",
          "platform_engineering": "平台工程",
          "body_layout_sealing_maintenance_access_and_payload_space": "机体布局、密封、维护通道与挂载空间按一个平台系统设计。",
          "motion_and_control": "运动与控制",
          "thruster_layout_depth_hold_and_operator_feedback_support": "推进器布局、定深和操作反馈支持稳定巡检输出。",
          "sensor_integration": "传感集成",
          "vision_sonar_water_quality_sensing_and_light_tools": "视觉、声呐、水质传感与轻作业工具按任务需要集成。",
          "delivery_support": "交付支持",
          "purchase_rental_field_support_and_payload_growth_follow": "采购、租赁、现场支持与挂载扩展沿同一交付路径推进。",
          "delivery_modes": "交付模式",
          "delivery_models": "交付模式",
          "delivery_is_matched_to_mission_scope_payload_work": "交付方式按任务范围、挂载工作和现场约束匹配",
          "purchase": "采购",
          "for_long_term_internal_operation_routine_inspection_and": "适合长期内部运行、常规巡检与自有设备规划。",
          "rental": "租赁",
          "for_short_projects_early_validation_stages_and_temporary": "适合短期项目、早期验证和临时现场部署。",
          "platform_operator_support_and_field_side_coordination_can": "可按实际任务匹配平台、操作支持与现场协调。",
          "project_expansion": "项目扩展",
          "add_sensing_support_frames_lighting_or_environment_modules": "围绕目标任务增加传感、支撑结构、照明或环境模块。",
          "beijing_squadot_technology_ltd": "北京方点科技有限公司",
          "underwater_rov_platforms_for_inspection_mission_support_and": "面向巡检、任务支持与挂载集成的水下 ROV 平台。",
          "contact": "联系",
          "define_the_mission_boundary": "定义任务边界",
          "share_depth_access_space_target_and_payload_expectations": "提供水深、进入空间、目标与挂载预期，开始技术沟通。",
          "contact_us": "联系我们"
        }
      },
      "products": {
        "meta": {
          "title": "产品 | Squadot Tec.",
          "description": "比较五类水下 ROV 平台，覆盖巡检、观测、受限空间进入与任务支持。"
        },
        "copy": {
          "products": "产品",
          "five_platforms_by_mission_boundary": "五个平台，按任务边界选型",
          "the_portfolio_spans_micro_to_medium_platforms_matched": "产品覆盖微型至中型平台，按水深、进入空间、观测目标、挂载需求与交付方式匹配。",
          "item_100_m_class_range": "100 m 级范围",
          "constrained_access": "受限进入",
          "purchase_rental": "采购 / 租赁",
          "compare_platforms": "比较平台",
          "start_with_depth_access_space_and_payload_direction": "先确认水深、进入空间与挂载方向，再进入平台细节。",
          "overview": "概览",
          "five_platforms_clear_selection_path": "五个平台，选型路径清晰",
          "medium_hybrid_rov": "中型混合 ROV",
          "item_100_m_class_platform_for_complex_waters_and": "100 m 级平台，面向复杂水域与挂载扩展。",
          "agile_observation_rov": "高机动观测 ROV",
          "for_fine_attitude_control_experiment_support_and_multi": "用于精细姿态控制、试验支持与多角度观测。",
          "close_range_work_rov": "近距作业 ROV",
          "six_thruster_base_with_an_upgrade_path_for": "六推进器基础，可扩展至八推进器作业逻辑。",
          "shallow_pilot_rov": "浅水先导 ROV",
          "portable_platform_for_short_shallow_water_checks_and": "便携平台，用于短周期浅水检查和快速入场。",
          "confined_access_rov": "受限空间 ROV",
          "item_10_m_class_unit_for_culverts_shafts_and": "10 m 级设备，用于涵洞、井室与箱涵。",
          "medium_hybrid_inspection_rov": "中型混合巡检 ROV",
          "designed_for_complex_water_inspection_mission_stability_and": "面向水库、大坝、近岸结构与环境监测中的复杂水域巡检、任务稳定性和挂载扩展。",
          "item_8_thrusters": "8 推进器",
          "multi_payload": "多挂载",
          "complex_waters": "复杂水域",
          "platform_role": "平台角色",
          "medium_hybrid_platform_for_inspection_observation_survey_support": "中型混合平台，用于巡检、观测、测绘支持与挂载型任务扩展。",
          "standard_configuration": "标准配置",
          "hd_visual_observation": "高清视觉观测",
          "depth_attitude_and_heading_feedback": "深度、姿态与航向反馈",
          "ground_station_monitoring": "地面站监控",
          "optional_modules": "可选模块",
          "dvl": "DVL",
          "scanning_sonar": "扫描声呐",
          "water_quality_multiparameter_sensing": "水质多参数传感",
          "manipulator_or_sampling_tools": "机械手或采样工具",
          "project_expansion": "项目扩展",
          "optional_binocular_vision_industrial_pc_edge_computing_and": "可选双目视觉、工控机、边缘计算与任务框架按项目范围处理；研发预留单独讨论。",
          "typical_tasks_structural_inspection_engineering_observation_complex_water": "典型任务：结构巡检、工程观测、复杂水域导航支持与多传感器集成。",
          "designed_for_maneuverability_multi_angle_viewing_fine_attitude": "面向机动性、多角度视野、精细姿态控制与水下试验支持设计。",
          "fine_attitude_control": "精细姿态控制",
          "data_collection": "数据采集",
          "compact_platform_for_fine_inspection_underwater_tests_research": "紧凑平台，用于精细巡检、水下试验、科研观测与工程复核。",
          "manual_control": "手动控制",
          "multi_axis_attitude_control": "多轴姿态控制",
          "manipulator": "机械手",
          "small_water_quality_sensors": "小型水质传感器",
          "additional_lighting": "附加照明",
          "custom_task_frames_external_modules_and_collection_attachments": "定制任务框架、外接模块与采集附件按项目范围处理。",
          "typical_tasks_precision_observation_experiment_support_multi_angle": "典型任务：精密观测、试验支持、多角度目标复核与紧凑深水巡检。",
          "work_class_inspection_rov": "工作级巡检 ROV",
          "close_range_platform_with_six_thruster_base_and": "近距平台，六推进器基础并具备八推进器升级路径，适用于水厂、泵站与闸室。",
          "depth_hold": "定深",
          "light_work": "轻作业",
          "for_close_inspection_stable_hovering_directional_review_and": "用于近距巡检、稳定悬停、定向复核与轻型附件扩展。",
          "basic_attitude_control": "基础姿态控制",
          "px4_ardusub_qgroundcontrol_control_path": "PX4 / ArduSub / QGroundControl 控制路径",
          "manipulator_claw": "机械爪",
          "gimbal": "云台",
          "lighting_system": "照明系统",
          "custom_tether_length": "定制缆长",
          "eight_thruster_upgrade_custom_interface_boards_and_task": "可面向轻作业场景提供八推进器升级、定制接口板与任务附件。",
          "typical_tasks_hydraulic_review_pump_station_inspection_gate": "典型任务：水工复核、泵站检查、闸室观测与近距视觉确认。",
          "portable_shallow_water_rov": "便携浅水 ROV",
          "fast_entry_platform_for_shallow_pilot_checks_short": "面向池塘、基坑、水槽和近岸浅水的浅水先导检查、短周期复核与试用部署。",
          "item_6_thrusters": "6 推进器",
          "fast_deployment": "快速部署",
          "for_shallow_pilot_checks_initial_judgement_short_reviews": "用于浅水先导检查、初步判断、短周期复核与低门槛入场。",
          "network_communication": "网络通信",
          "portable_pvc_tube_structure_logic": "便携 PVC 管结构逻辑",
          "visual_add_ons": "视觉扩展",
          "lighting": "照明",
          "shallow_water_sensing_modules": "浅水传感模块",
          "quick_release_accessories_collision_protection_and_shallow_water": "可在现场配置快拆附件、防碰结构与浅水检测模块。",
          "typical_tasks_shallow_pilot_checks_pond_review_short": "典型任务：浅水先导检查、池体复核、短期验证与快速入场。",
          "compact_confined_access_rov": "紧凑受限空间 ROV",
          "constrained_access_unit_for_culverts_gate_slots_shafts": "面向涵洞、闸槽、井室、箱涵等浅水工业空间的受限进入设备。",
          "lightweight": "轻量化",
          "for_close_visual_review_anomaly_confirmation_and_rapid": "用于狭窄浅水空间的近距视觉复核、异常确认与快速进入。",
          "lightweight_compact_body": "轻量紧凑机身",
          "shallow_water_video_observation": "浅水视频观测",
          "rapid_single_operator_deployment_logic": "单人快速部署逻辑",
          "shallow_water_water_quality_sensing": "浅水水质传感",
          "small_manipulator_tools": "小型机械手工具",
          "collision_protection_structures_narrow_space_brackets_and_lightweight": "可按项目配置防碰结构、窄空间支架与轻量任务附件。",
          "typical_tasks_culvert_review_shaft_inspection_shallow_anomaly": "典型任务：涵洞复核、井室巡检、浅水异常确认与受限空间先导检查。",
          "support_logic": "支持逻辑",
          "standard_first_mission_growth_second": "先标准平台，再任务扩展",
          "most_projects_should_start_with_a_deliverable_standard": "多数项目应先从可交付标准平台开始，只在传感、结构或交付方式需要时扩展。",
          "standard_platform": "标准平台",
          "use_the_current_direct_delivery_platform_as_the": "以当前可直接交付的平台作为第一匹配基础。",
          "module_growth": "模块扩展",
          "add_sensing_lighting_sampling_or_support_frames_only": "仅在任务需要时增加感知、照明、采样或支撑结构。",
          "delivery_alignment": "交付匹配",
          "purchase_rental_or_mission_support_should_follow_task": "采购、租赁或任务支持应跟随任务周期与现场强度。",
          "first_platform_recommendation": "第一轮平台建议",
          "share_depth_range_entry_size_and_payload_direction": "提供水深范围、入口尺寸与挂载方向，用于收敛平台路径。",
          "start_with_your_mission": "从任务开始",
          "beijing_squadot_technology_ltd": "北京方点科技有限公司",
          "five_platform_product_range_for_inspection_observation_and": "面向巡检、观测与任务支持的五平台产品线。",
          "selection_logic": "选型逻辑",
          "select_by_mission_boundary": "按任务边界选型",
          "share_depth_access_space_target_payload_needs_and": "提供水深、进入空间、目标、挂载需求与交付方式，用于识别平台系列。"
        }
      },
      "applications": {
        "meta": {
          "title": "场景 | Squadot Tec.",
          "description": "按水深、进入空间、目标、稳定性与挂载需求匹配水下 ROV 平台。"
        },
        "copy": {
          "applications": "应用场景",
          "select_platforms_by_scene_constraints": "按场景约束选择平台",
          "scenes_are_organized_by_operating_depth_access_space": "场景按作业水深、进入空间、目标、稳定性与挂载需求组织。",
          "depth_range": "水深范围",
          "space_limit": "空间限制",
          "payload_need": "挂载需求",
          "view_selection_logic": "查看选型逻辑",
          "use_site_conditions_to_narrow_platform_fit_before": "先用现场条件缩小平台范围，再进入硬件比较。",
          "matching_logic": "匹配逻辑",
          "four_inputs_for_platform_fit": "四项输入确定平台适配",
          "depth_hovering_and_operating_duration_quickly_separate_platform": "水深、悬停与作业时长会快速区分平台系列。",
          "space_boundary": "空间边界",
          "open_water_culverts_shafts_and_gate_slots_require": "开阔水域、涵洞、井室与闸槽对应不同进入逻辑。",
          "observation_demand": "观测需求",
          "routine_review_precision_observation_and_experiment_support_require": "常规复核、精细观测与试验支持需要不同稳定性等级。",
          "payload_and_delivery": "挂载与交付",
          "some_missions_need_only_video_others_require_sonar": "有些任务只需视频，有些需要声呐、传感、挂载或现场支持。",
          "scene_01": "场景 01",
          "ports_and_nearshore_assets": "港口与近岸资产",
          "low_visibility_piles_cables_sediment_or_path_support": "低能见度、桩基、缆线、淤积或路径辅助需求会超出基础视频复核。",
          "client_problem": "客户问题",
          "single_view_observation_is_often_insufficient_in_structure": "结构密集水域中，单视角观测通常不足以支撑判断。",
          "recommended_platform": "推荐平台",
          "sealeopard_with_sonar_dvl_or_environmental_sensing_when": "SeaLeopard，可按需配置声呐、DVL 或环境感知模块。",
          "delivery_platform_sensing_module_and_mission_support_product": "交付：平台、感知模块与任务支持。产品：SeaLeopard。",
          "scene_02": "场景 02",
          "dams_and_hydraulic_assets": "大坝与水工资产",
          "these_tasks_require_stable_close_viewing_depth_hold": "任务需要稳定近距观察、定深控制与状态确认，减少对潜水员先行进入的依赖。",
          "operators_need_clear_target_surface_imagery_while_holding": "操作者需要在稳定观察距离下获得清晰目标表面图像。",
          "challenge_for_routine_work_class_review_sealeopard_where": "常规工作级复核采用 Challenge；需要更高挂载或稳定性时采用 SeaLeopard。",
          "delivery_purchase_or_mission_support_depending_on_task": "交付：按任务频次选择采购或任务支持。",
          "scene_03": "场景 03",
          "precision_observation_and_underwater_tests": "精密观测与水下试验",
          "these_missions_require_fine_attitude_control_repeatable_response": "任务需要精细姿态控制、可重复响应与稳定目标对准。",
          "observation_quality_drops_quickly_when_posture_stability_is": "姿态稳定性不足时，观测质量会迅速下降。",
          "hammerhead_with_multi_axis_control_and_task_specific": "Hammerhead，配置多轴控制与任务专用支撑结构。",
          "delivery_rental_test_support_or_project_expansion_around": "交付：围绕试验装置提供租赁、测试支持或项目扩展。",
          "scene_04": "场景 04",
          "shallow_pilot_checks_and_tanks": "浅水先导检查与池体",
          "fast_deployment_and_low_operating_threshold_matter_more": "快速部署和低操作门槛比重型挂载能力更重要。",
          "large_platforms_are_often_unnecessary_in_ponds_pits": "池塘、基坑和试验水槽中，大型平台往往没有必要。",
          "inspire_for_quick_entry_and_shallow_water_review": "Inspire，用于快速进入与浅水复核。",
          "delivery_rental_or_short_mission_support_for_pilot": "交付：租赁或短期任务支持，用于先导判断与验证。",
          "scene_05": "场景 05",
          "confined_industrial_spaces": "受限工业空间",
          "culverts_gate_slots_shafts_box_channels_and_tanks": "涵洞、闸槽、井室、箱涵与罐体优先考虑紧凑进入，而非开阔水域机动性。",
          "large_platforms_cannot_enter_reliably_but_anomaly_confirmation": "大型平台难以可靠进入，但仍需完成异常确认。",
          "linglong_first_inspire_when_the_space_is_less": "优先选择 Linglong；空间较宽且任务仍属浅水时可选 Inspire。",
          "delivery_portable_inspection_support_shallow_anomaly_review_and": "交付：便携巡检支持、浅水异常复核与轻量模块扩展。",
          "scene_based_recommendation": "场景化建议",
          "start_with_depth_entry_size_target_and_payload": "从水深、入口尺寸、目标和挂载预期开始。",
          "start_the_discussion": "开始沟通",
          "beijing_squadot_technology_ltd": "北京方点科技有限公司",
          "scene_led_platform_matching_for_underwater_inspection_and": "面向水下巡检与观测的场景化平台匹配。",
          "next_step": "下一步",
          "site_specific_platform_direction": "现场专属平台方向",
          "provide_depth_entry_size_target_and_payload_expectations": "提供水深、入口尺寸、目标与挂载预期，用于确定第一轮平台方向。",
          "start_contact": "开始联系"
        }
      },
      "capabilities": {
        "meta": {
          "title": "能力 | Squadot Tec.",
          "description": "查看平台设计、密封耐压、控制、传感集成与任务交付能力。"
        },
        "copy": {
          "capabilities": "能力",
          "platform_control_mission_integration": "平台、控制与任务集成",
          "capability_is_organized_around_platform_design_sealing_control": "能力围绕平台设计、水密密封、控制、挂载集成与现场支持组织。",
          "platform_body": "平台本体",
          "control_loop": "控制闭环",
          "mission_integration": "任务集成",
          "view_capability_layers": "查看能力层级",
          "review_standard_capability_optional_modules_and_project_expansion": "按层级查看标准能力、可选模块与项目扩展。",
          "core_capability": "核心能力",
          "six_capability_blocks": "六项能力模块",
          "platform_engineering": "平台工程",
          "structure_size_envelope_internal_layout_and_maintenance_access": "结构、尺寸边界、内部布局与维护通道按一个平台系统设计。",
          "sealing_and_pressure_logic": "密封与耐压逻辑",
          "reliable_underwater_use_depends_on_sealing_cable_entry": "可靠水下使用依赖密封、线缆入口与维护逻辑，而不是孤立防水部件。",
          "propulsion_and_motion_control": "推进与运动控制",
          "thruster_layout_depth_hold_and_stable_viewing_behavior": "推进器布局、定深和稳定观察行为决定巡检质量。",
          "ground_station_and_operator_loop": "地面站与操作闭环",
          "monitoring_operator_feedback_and_task_adjustment_must_stay": "监控、操作反馈与任务调整需要保持在同一控制闭环内。",
          "payload_and_sensor_integration": "挂载与传感集成",
          "video_sonar_sampling_water_quality_sensing_and_manipulator": "视频、声呐、采样、水质传感与机械手任务按需求集成。",
          "mission_support_and_project_expansion": "任务支持与项目扩展",
          "platform_selection_field_support_and_project_expansion_are": "平台选型、现场支持与项目扩展属于整体交付范围。",
          "capability_layer": "能力层级",
          "standard_optional_and_project_layers": "标准、可选与项目层级",
          "layered_capability_keeps_standard_configuration_optional_modules_and": "分层能力让标准配置、可选模块和项目支持保持清晰。",
          "layer_01": "层级 01",
          "standard_configuration_deliverable_platform_capability": "标准配置：可直接交付的平台能力。",
          "layer_02": "层级 02",
          "optional_modules_add_ons_that_do_not_require": "可选模块：不需要重新设计平台的附加模块。",
          "layer_03": "层级 03",
          "project_expansion_mission_driven_frames_interfaces_and_system": "项目扩展：由任务驱动的结构、接口与系统调整。",
          "layer_04": "层级 04",
          "r_and_d_reserve_discussed_separately_not_a": "研发预留：单独讨论，不作为默认交付承诺。",
          "delivery_models": "交付模式",
          "capability_mapped_to_delivery": "能力映射到交付",
          "platform_purchase": "平台采购",
          "for_users_building_regular_in_house_inspection_and": "适合建立常态化内部巡检与观测能力的用户。",
          "equipment_rental": "设备租赁",
          "for_short_cycle_missions_validation_work_and_temporary": "适合短周期任务、验证工作与临时现场复核。",
          "mission_support": "任务支持",
          "for_customers_who_need_platform_plus_field_side": "适合需要平台加现场操作或技术协调的客户。",
          "project_expansion": "项目扩展",
          "for_missions_that_require_sensing_brackets_environment_modules": "适合需要传感、支架、环境模块或定制接口的任务。",
          "discuss_capability_by_layer_then_map_it_to": "先按层级讨论能力，再映射到水深、进入空间与挂载需求。",
          "capability_match": "能力匹配",
          "start_with_depth_scene_and_payload_expectations_to": "从水深、场景和挂载预期开始，缩小可用能力层级。",
          "start_capability_match": "开始能力匹配",
          "beijing_squadot_technology_ltd": "北京方点科技有限公司",
          "engineering_capability_across_platform_control_sensing_and_field": "覆盖平台、控制、感知与现场交付的工程能力。",
          "contact": "联系",
          "mission_based_capability_match": "基于任务的能力匹配",
          "start_with_depth_entry_space_target_and_module": "从水深、入口空间、目标与模块需求开始，匹配能力层级和交付路径。",
          "start_contact": "开始联系"
        }
      },
      "cases": {
        "meta": {
          "title": "案例 | Squadot Tec.",
          "description": "查看近岸巡检、水工结构、试验支持、浅水检查与受限空间进入的代表案例。"
        },
        "copy": {
          "cases": "案例",
          "cases_by_mission_type": "按任务类型整理案例",
          "representative_cases_show_platform_fit_observation_quality_control": "代表性案例展示平台适配、观测质量、控制行为与交付范围。",
          "scene_fit": "场景适配",
          "control_quality": "控制质量",
          "delivery_path": "交付路径",
          "browse_cases": "浏览案例",
          "use_each_case_as_a_reference_for_similar": "每个案例可作为相近现场条件与交付需求的参考。",
          "case_01": "案例 01",
          "nearshore_inspection": "近岸结构巡检",
          "for_structure_rich_waters_where_path_support_environment": "面向结构密集水域，重点关注路径辅助、环境感知与碰撞风险降低。",
          "client_problem": "客户问题",
          "piles_cables_sediment_and_low_visibility_make_single": "桩基、缆线、淤积和低能见度使单一观测模式不足。",
          "platform_capability": "平台 / 能力",
          "sealeopard_with_scanning_sonar_dvl_and_environmental_sensing": "SeaLeopard，可按需配置扫描声呐、DVL 与环境感知。",
          "value_stronger_environment_awareness_and_path_support_logic": "价值：增强环境感知与路径辅助逻辑。产品：SeaLeopard。",
          "case_02": "案例 02",
          "precision_observation": "精密观测",
          "focused_on_precise_operator_response_controlled_posture_and": "聚焦精确操作响应、受控姿态与可重复目标对准。",
          "observation_quality_depends_directly_on_posture_stability_and": "观测质量直接依赖姿态稳定和角度控制。",
          "hammerhead_with_multi_axis_motion_control_and_task": "Hammerhead，配置多轴运动控制与任务专用支撑结构。",
          "value_better_posture_stability_and_execution_precision_product": "价值：提升姿态稳定性与执行精度。产品：Hammerhead。",
          "case_03": "案例 03",
          "hydraulic_inspection": "水工巡检",
          "routine_structural_review_where_close_range_imaging_and": "常规结构复核，近距成像和稳定悬停比复杂挂载更重要。",
          "the_structure_must_be_inspected_without_organizing_diver": "需要在不组织潜水员先行进入的情况下完成结构检查。",
          "challenge_with_hd_visual_observation_depth_hold_and": "Challenge，提供高清视觉观测、定深与地面站监控。",
          "value_reviewable_structure_records_for_follow_up_maintenance": "价值：形成可复核的结构记录，支持后续维护。产品：Challenge。",
          "case_04": "案例 04",
          "shallow_pilot_checks": "浅水先导检查",
          "for_quick_judgement_close_review_and_fast_entry": "面向快速判断、近距复核和快速入场，小型可部署平台更高效。",
          "the_work_is_short_cycle_and_does_not": "任务周期短，不适合调动大型装备。",
          "inspire_with_fast_deployment_network_communication_and_six": "Inspire，具备快速部署、网络通信与六推进器浅水控制。",
          "value_fast_first_pass_judgement_and_low_threshold": "价值：快速形成第一轮判断，降低现场复核门槛。产品：Inspire。",
          "case_05": "案例 05",
          "confined_space_inspection": "受限空间巡检",
          "when_culverts_shafts_gate_slots_or_box_channels": "当涵洞、井室、闸槽或箱涵让入口尺寸成为主要选型因素。",
          "large_platforms_cannot_enter_but_local_anomaly_review": "大型平台无法进入，但仍需完成局部异常复核和记录。",
          "linglong_with_compact_body_shallow_water_video_review": "Linglong，具备紧凑机身、浅水视频复核与快速部署。",
          "value_lower_entry_threshold_and_faster_anomaly_confirmation": "价值：降低进入门槛，加快异常确认。产品：Linglong。",
          "case_value": "案例价值",
          "what_cases_clarify": "案例说明什么",
          "each_case_highlights_scene_fit_execution_method_and": "每个案例突出场景适配、执行方式与可用交付范围。",
          "mission_fit": "任务适配",
          "case_descriptions_are_organized_around_scene_conditions_and": "案例描述围绕现场条件与平台适配组织。",
          "scope_clarity": "范围清晰",
          "the_page_focuses_on_representative_mission_profiles_rather": "页面聚焦代表性任务画像，而非目录式罗列。",
          "capability_proof": "能力验证",
          "each_case_shows_platform_fit_control_quality_and": "每个案例体现平台适配、控制质量与任务集成逻辑。",
          "next_step": "下一步",
          "the_page_is_designed_to_support_discussion_around": "页面用于支持围绕相近现场条件和输出目标的沟通。",
          "similar_mission_discussion": "相近任务沟通",
          "share_site_conditions_and_desired_output_to_map": "提供现场条件与期望输出，用于匹配最接近的平台和支持方式。",
          "start_the_discussion": "开始沟通",
          "beijing_squadot_technology_ltd": "北京方点科技有限公司",
          "mission_aligned_cases_for_underwater_observation_inspection_and": "面向水下观测、巡检与任务支持的任务型案例。",
          "contact": "联系",
          "comparable_mission_profile": "相近任务画像",
          "send_site_conditions_and_desired_output_to_map": "发送现场条件和期望输出，用于匹配最接近的平台与支持模式。",
          "start_contact": "开始联系"
        }
      },
      "about": {
        "meta": {
          "title": "关于 | Squadot Tec.",
          "description": "了解 Squadot Tec. 面向水下机器人平台与任务交付的产品化工程能力。"
        },
        "copy": {
          "about_squadot_tec": "关于 Squadot Tec.",
          "engineering_team_for_underwater_systems": "水下系统工程团队",
          "squadot_tec_focuses_on_underwater_observation_structural_inspection": "Squadot Tec. 聚焦水下观测、结构巡检、受限空间进入、浅水复核与任务挂载集成。",
          "engineering_team": "工程团队",
          "platform_delivery": "平台交付",
          "project_growth": "项目扩展",
          "see_team_logic": "查看团队逻辑",
          "understand_the_team_through_platform_engineering_sensing_control": "从平台工程、感知、控制与交付方式理解团队能力。",
          "identity": "团队定位",
          "productized_engineering_team": "产品化工程团队",
          "productized_engineering_team_for_underwater_robot_platforms_and": "面向水下机器人平台与任务支持的产品化工程团队。",
          "current_offering": "当前提供",
          "micro_to_medium_platforms_rental_purchase_field_support": "微型至中型平台，以及采购、租赁、现场支持和挂载集成。",
          "scene_focus": "场景聚焦",
          "hydraulic_structures_nearshore_assets_ponds_shafts_culverts_and": "覆盖水工结构、近岸资产、池体、井室、涵洞与受限工业水域。",
          "delivery_logic": "交付逻辑",
          "begin_with_a_standard_platform_then_expand_payloads": "先匹配标准平台，再按任务扩展挂载、结构件与交付方式。",
          "team_background": "团队背景",
          "platform_sensing_control_delivery": "平台、感知、控制、交付",
          "engineering_background": "工程背景",
          "team_background_spans_acoustics_underwater_robotics_navigation_slam": "团队背景覆盖声学、水下机器人、导航、SLAM 与水下系统设计。",
          "platform_engineering": "平台工程",
          "capability_covers_rov_auv_structure_design_watertight_components": "能力覆盖 ROV/AUV 结构设计、水密部件、控制系统与现场部署。",
          "perception_and_navigation": "感知与导航",
          "work_covers_sonar_slam_path_planning_image_enhancement": "工作覆盖声呐 SLAM、路径规划、图像增强与多传感器融合。",
          "system_integration": "系统集成",
          "software_integration_ground_station_monitoring_and_field_execution": "软件集成、地面站监控与现场执行共同构成交付体系。",
          "company_approach": "公司方法",
          "standard_platform_first_mission_growth_second": "先标准平台，再任务扩展",
          "step_01": "步骤 01",
          "choose_the_closest_standard_platform_by_depth_access": "按水深、进入空间与运动需求选择最接近的标准平台。",
          "step_02": "步骤 02",
          "add_sensing_lighting_sampling_or_support_frames_only": "仅在任务需要时增加感知、照明、采样或支撑结构。",
          "step_03": "步骤 03",
          "align_purchase_rental_or_mission_support_with_the": "按项目周期匹配采购、租赁或任务支持方式。",
          "engineering_discussion": "工程沟通",
          "share_site_conditions_delivery_mode_and_module_expectations": "提供现场条件、交付方式与模块预期，用于确定合适路径。",
          "start_contact": "开始联系",
          "beijing_squadot_technology_ltd": "北京方点科技有限公司",
          "productized_engineering_team_for_underwater_robot_systems_and": "面向水下机器人系统与任务支持的产品化工程团队。",
          "contact": "联系",
          "mission_boundary": "任务边界",
          "start_with_depth_entry_size_target_type_and": "从水深、入口尺寸、目标类型与模块预期开始。"
        }
      },
      "contact": {
        "meta": {
          "title": "联系 | Squadot Tec.",
          "description": "请提供水深、进入空间、观测目标、挂载需求与交付周期，便于快速匹配平台方向。"
        },
        "copy": {
          "contact": "联系",
          "start_with_depth_access_and_payload": "从水深、空间和挂载开始",
          "the_most_useful_first_inputs_are_operating_depth": "第一轮最有效的信息是作业水深、入口尺寸、观测目标、挂载需求与交付周期。",
          "depth_range": "水深范围",
          "entry_size": "入口尺寸",
          "delivery_timeline": "交付周期",
          "view_contact_info": "查看联系方式",
          "a_short_mission_brief_is_enough_to_begin": "一份简短任务说明即可开始平台匹配。",
          "direct_contact": "直接联系",
          "company": "公司",
          "squadot_tec": "Squadot Tec.",
          "beijing_squadot_technology_ltd": "北京方点科技有限公司",
          "website": "官网",
          "phone": "电话",
          "address": "地址",
          "room_3129_no_86_huoxing_north_street_huoxian": "北京市通州区漷县镇漷兴北大街86号院3129室",
          "mission_brief": "任务说明",
          "six_inputs_for_the_first_brief": "首轮沟通六项信息",
          "item_01_depth_range": "01. 水深范围",
          "operating_depth_and_whether_depth_hold_is_required": "作业水深，以及是否需要定深。",
          "item_02_entry_size": "02. 入口尺寸",
          "opening_size_channel_width_and_whether_the_site": "开口尺寸、通道宽度，以及现场是否属于受限空间。",
          "item_03_observation_target": "03. 观测目标",
          "structure_sediment_anomaly_point_test_setup_or_environmental": "结构、淤积、异常点、试验装置或环境状态。",
          "item_04_payload_need": "04. 挂载需求",
          "video_only_or_additional_sonar_sampling_water_quality": "仅视频，或需要声呐、采样、水质、机械手等附加模块。",
          "item_05_delivery_model": "05. 交付方式",
          "purchase_rental_short_field_support_or_project_specific": "采购、租赁、短期现场支持或项目化开发。",
          "item_06_timeline": "06. 时间计划",
          "start_date_and_whether_the_work_is_one": "启动时间，以及任务是一次性还是周期性。",
          "contact_base": "联系基础",
          "project_communication_channels": "项目沟通渠道",
          "use_phone_website_and_company_address_to_start": "通过电话、官网和公司地址，围绕任务条件与交付需求开展聚焦沟通。",
          "chinese_address": "中文地址",
          "english_address": "英文地址",
          "first_mission_brief": "首轮任务说明",
          "call_directly_or_send_a_short_mission_brief": "可直接电话联系，也可通过官网渠道发送简短任务说明。",
          "call_now": "立即联系",
          "underwater_robot_platforms_mission_support_and_project_specific": "水下机器人平台、任务支持与项目化集成。",
          "talk_to_us": "与我们沟通",
          "initial_platform_direction": "第一轮平台方向"
        }
      }
    }
  }
};
